import { ScreeningRecord, SecurityAlert, OfficerProfile } from '../types';

export const mockOfficer: OfficerProfile = {
  id: 'SSB-OFC-8821',
  name: 'Officer Rajesh Verma',
  rank: 'Assistant Commandant',
  unit: '14th Battalion SSB (Indo-Nepal Border)',
  checkpoint: 'CHK-00184 (Raxaul Integrated Checkpost)',
  securityClearance: 'SECRET / OPERATIONAL GRADE-1',
  role: 'checkpoint',
};

export const initialRecords: ScreeningRecord[] = [
  {
    id: 'VF-28491',
    name: 'Aditi Sharma',
    docType: 'Aadhaar Card',
    docNumber: 'XXXX-XXXX-9281',
    status: 'VERIFIED',
    timestamp: '09:42 AM',
    checkpointId: 'CHK-00184',
    officerId: 'SSB-OFC-8821',
    gender: 'F',
    dob: '14-06-1994',
    address: 'Sector 4, Gandhinagar, Gujarat - 382004',
    nationality: 'Indian',
    matchScore: 99.2,
    ocrConfidence: 99.8,
    securityChecks: {
      hologramDetected: true,
      tamperingDetected: false,
      watchlistMatch: false,
      biometricMatch: true,
    },
    notes: 'Standard citizen border transit. Identity verified against UIDAI ledger.',
  },
  {
    id: 'VF-28490',
    name: 'Arjun Singh',
    docType: 'Border Pass',
    docNumber: 'BP-IN-NP-8831',
    status: 'NEEDS_REVIEW',
    timestamp: '09:18 AM',
    checkpointId: 'CHK-00183',
    officerId: 'SSB-OFC-8821',
    gender: 'M',
    dob: '02-11-1988',
    address: 'Birgunj Border Sector, Ward 3, Parsa',
    nationality: 'Nepalese',
    matchScore: 84.1,
    ocrConfidence: 91.0,
    securityChecks: {
      hologramDetected: true,
      tamperingDetected: false,
      watchlistMatch: false,
      biometricMatch: false,
    },
    notes: 'Secondary biometric mismatch on facial aging index. Requires manual officer interview.',
  },
  {
    id: 'VF-28489',
    name: 'Priya Patel',
    docType: 'Passport',
    docNumber: 'Z8921849',
    status: 'MISMATCH',
    timestamp: '08:56 AM',
    checkpointId: 'CHK-00182',
    officerId: 'SSB-OFC-8821',
    gender: 'F',
    dob: '19-08-1991',
    address: 'Navrangpura, Ahmedabad, Gujarat',
    nationality: 'Indian',
    matchScore: 42.6,
    ocrConfidence: 78.4,
    securityChecks: {
      hologramDetected: false,
      tamperingDetected: true,
      watchlistMatch: false,
      biometricMatch: false,
    },
    notes: 'Security thread anomalies detected under UV wavelength check. Machine readable zone (MRZ) checksum failed.',
  },
  {
    id: 'VF-28488',
    name: 'Mohd. Farooq Tariq',
    docType: 'Passport',
    docNumber: 'P4492019',
    status: 'HIGH_RISK',
    timestamp: '08:12 AM',
    checkpointId: 'CHK-00184',
    officerId: 'SSB-OFC-8821',
    gender: 'M',
    dob: '05-01-1982',
    address: 'Civil Lines, Moradabad, Uttar Pradesh',
    nationality: 'Indian',
    matchScore: 31.0,
    ocrConfidence: 96.5,
    securityChecks: {
      hologramDetected: false,
      tamperingDetected: true,
      watchlistMatch: true,
      biometricMatch: false,
    },
    notes: 'CRITICAL ALERT: Biometric facial query matched IB & NIA central alert circular #LOC-2026-904. Subject detained at Holding Bay 2.',
  },
  {
    id: 'VF-28487',
    name: 'Vikramaditya Roy',
    docType: 'Driving License',
    docNumber: 'DL-0420190038192',
    status: 'VERIFIED',
    timestamp: '07:45 AM',
    checkpointId: 'CHK-00184',
    officerId: 'SSB-OFC-8821',
    gender: 'M',
    dob: '23-03-1985',
    address: 'Salt Lake City, Sector V, Kolkata, WB',
    nationality: 'Indian',
    matchScore: 97.8,
    ocrConfidence: 98.2,
    securityChecks: {
      hologramDetected: true,
      tamperingDetected: false,
      watchlistMatch: false,
      biometricMatch: true,
    },
    notes: 'Commercial transit vehicle operator clearance.',
  },
  {
    id: 'VF-28486',
    name: 'Sunita Devi Yadav',
    docType: 'Voter ID',
    docNumber: 'EPIC-BR-492810',
    status: 'VERIFIED',
    timestamp: '07:20 AM',
    checkpointId: 'CHK-00181',
    officerId: 'SSB-OFC-8821',
    gender: 'F',
    dob: '10-12-1979',
    address: 'Village Siswa, Motihari, East Champaran, Bihar',
    nationality: 'Indian',
    matchScore: 95.4,
    ocrConfidence: 94.0,
    securityChecks: {
      hologramDetected: true,
      tamperingDetected: false,
      watchlistMatch: false,
      biometricMatch: true,
    },
    notes: 'Daily local border trade permit verified.',
  }
];

export const samplePresetDocuments = [
  {
    title: 'Aditi Sharma (Valid Aadhaar)',
    type: 'Aadhaar Card' as const,
    docNumber: 'XXXX-XXXX-9281',
    name: 'Aditi Sharma',
    dob: '14-06-1994',
    gender: 'F' as const,
    nationality: 'Indian',
    address: 'Sector 4, Gandhinagar, Gujarat - 382004',
    matchScore: 99.2,
    ocrConfidence: 99.8,
    status: 'VERIFIED' as const,
    securityChecks: {
      hologramDetected: true,
      tamperingDetected: false,
      watchlistMatch: false,
      biometricMatch: true,
    },
    notes: 'Document authenticated with UIDAI digital signature. Biometric face liveness verified.',
  },
  {
    title: 'Rohit Kumar (Suspect Passport - Expired Visa)',
    type: 'Passport' as const,
    docNumber: 'Z1904821',
    name: 'Rohit Kumar',
    dob: '11-04-1990',
    gender: 'M' as const,
    nationality: 'Indian',
    address: 'Model Town, Panipat, Haryana',
    matchScore: 68.4,
    ocrConfidence: 89.1,
    status: 'NEEDS_REVIEW' as const,
    securityChecks: {
      hologramDetected: true,
      tamperingDetected: false,
      watchlistMatch: false,
      biometricMatch: false,
    },
    notes: 'Entry stamp ink density disparity. Border immigration clearance requires supervisor signature.',
  },
  {
    title: 'Unknown / Fake ID (Tampered Hologram)',
    type: 'Border Pass' as const,
    docNumber: 'BP-NP-2026-X99',
    name: 'Rajesh Manandhar',
    dob: '01-01-1980',
    gender: 'M' as const,
    nationality: 'Nepalese',
    address: 'Kathmandu Metro, Sector 9',
    matchScore: 34.0,
    ocrConfidence: 71.2,
    status: 'MISMATCH' as const,
    securityChecks: {
      hologramDetected: false,
      tamperingDetected: true,
      watchlistMatch: false,
      biometricMatch: false,
    },
    notes: 'Physical security foil missing. Digital watermark failed cryptographic checksum.',
  },
  {
    title: 'High Risk Watchlist Subject (LOC Issued)',
    type: 'Passport' as const,
    docNumber: 'P9028114',
    name: 'Mohd. Tariq',
    dob: '05-01-1982',
    gender: 'M' as const,
    nationality: 'Indian',
    address: 'Civil Lines, Moradabad, UP',
    matchScore: 98.9,
    ocrConfidence: 99.1,
    status: 'HIGH_RISK' as const,
    securityChecks: {
      hologramDetected: true,
      tamperingDetected: false,
      watchlistMatch: true,
      biometricMatch: true,
    },
    notes: 'CRITICAL MATCH: Central Watchlist hit (Look Out Circular #LOC-2026-904). Initiate immediate checkpoint security protocol.',
  }
];

export const initialAlerts: SecurityAlert[] = [
  {
    id: 'ALT-904',
    title: 'CRITICAL: Look Out Circular Hit at Sector 4',
    description: 'Biometric AI matched watchlist alert for suspect transit via Raxaul checkpoint.',
    severity: 'CRITICAL',
    timestamp: '12 min ago',
    location: 'Checkpoint CHK-00184',
    acknowledged: false,
    docRef: 'VF-28488',
  },
  {
    id: 'ALT-903',
    title: 'Tampered Passport Batch Detected',
    description: 'Multiple passports with fraudulent laminated stamps reported at Indo-Nepal transit zone.',
    severity: 'WARNING',
    timestamp: '1 hour ago',
    location: 'Sonauli Sector',
    acknowledged: true,
  },
  {
    id: 'ALT-902',
    title: 'Optical Scanner Firmware Updated',
    description: 'Spectral UV & IR neural model v4.2 calibrated for real-time hologram verification.',
    severity: 'INFO',
    timestamp: '3 hours ago',
    location: 'HQ Central Command',
    acknowledged: true,
  },
  {
    id: 'ALT-901',
    title: 'High Transit Volume Warning',
    description: 'Vehicle & pedestrian queue exceeding standard threshold at Raxaul North Gate.',
    severity: 'WARNING',
    timestamp: '5 hours ago',
    location: 'Checkpoint CHK-00184',
    acknowledged: true,
  }
];
